config/routes.rb
Rails.application.routes.draw do
  resources :attendances
  resources :events
  # resources :users, only: [:new, :create]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'attend/:id', to: 'events#attend', as: 'attendy'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  get 'attend', to: 'sessions#attend'
  resources :users
  resources :sessions
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# class to create a new table attendances
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: true
  has_many :events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :attendances, foreign_key: 'attendee_id'
  has_many :attended_events, through: :attendances, source: :attended_event, class_name: 'Event', dependent: :destroy
end

app/controllers/users_controller.rb
# class to create a new table attendances
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authorized, only: %i[edit show destroy update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @events = Event.all
    @user = User.find_by(username: params[:username])
    @next_events = current_user.attended_events.upcoming_events
    @prev_events = current_user.attended_events.previous_events
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to welcome_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :username, :email, :password)
  end
end

app/helpers/users_helper.rb
# class to create a new table attendances
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid text-center d-flex align-items-center justify-content-center">
  <h1 class="text-uppercase text-success">Welcome to Private Events</h1>
</div>
<div class="container-fluid border border-info text-center d-flex align-items-center justify-content-center">
  <h3 class="text-uppercase text-info">Members</h3>
</div>
<div class="container-fluid">
  <div class="row d-flex align-items-center justify-content-center">
    <div class="col-6 d-flex align-items-center justify-content-center">
      <%= link_to 'Sign In', login_path, class:'text-uppercase text-light border border-light pl-3 pr-3 pt-1 pb-1 bg-info' %>
    </div>
    <div class="col-6 d-flex align-items-center justify-content-center">
      <%= link_to 'Sign Up', new_user_path, class:'text-uppercase text-light border border-light pl-3 pr-3 pt-1 pb-1 bg-info' %>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row border d-flex align-items-center border-info">
    <div class="col-6 text-center">
      <h2 class="text-uppercase">Name</h2>
    </div>
    <div class="col-6 text-center">
      <h2 class="text-uppercase">Username</h2>
    </div>
  </div>
  <div class="row border border-info d-flex">
    <div class="col-6 text-center d-flex flex-column">
      <% @users.each do |u| %>
        <p><%= u.name%></p>
      <% end %>
    </div>
    <div class="col-6 text-center d-flex flex-column">
      <% @users.each do |i| %>
        <p><%= i.username %></p>
      <% end %> 
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<% if @events.any?%>
  <% @events.each do |event| %>
      <tr>
        <td><%= event.event_name %></td>
        <td><%= event.description %></td>
        <td><%= event.date %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
<% end %>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<%= link_to 'Events Availabe', events_path %> <br>

<div class="container-fluid">
  <div class="row border d-flex align-items-center border-info">
    <div class="col-3 text-center">
      <h2 class="text-uppercase">Events created by me</h2>
    </div>
    <div class="col-3 text-center">
      <h2 class="text-uppercase">My list of events</h2>
    </div>
    <div class="col-3 text-center">
      <h2 class="text-uppercase">My previous events</h2>
    </div>
    <div class="col-3 text-center">
      <h2 class="text-uppercase">My upcoming events</h2>
    </div>
  </div>
  <div class="row border border-info d-flex">
    <div class="col-3 text-center d-flex flex-column">
      <% current_user.events.each do |event| %>
        <%= event.description%>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <br>
      <% end %>
    </div>

    <div class="col-3 text-center d-flex flex-column">
      <% if @events.any?%>
        <% @events.each do |i|%>
          <% current_user.attended_events.ids.each do |id|%>
            <% if i.id == id%>
            <%= i.description%>
            <br>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <div class="col-3 text-center d-flex flex-column">
      <% @prev_events.each do |prev|%>
        <%= prev.description%>
        <br>
      <% end %>
    </div>

    <div class="col-3 text-center d-flex flex-column">
      <% @next_events.each do |fut|%>
        <%= fut.description%>
        <br>
      <% end %>
    </div>
  </div>
</div>