config/routes.rb
Rails.application.routes.draw do
  resources :attendances
  resources :events
  # resources :users, only: [:new, :create]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'attend/:id', to: 'events#attend', as: 'attendy'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  get 'attend', to: 'sessions#attend'
  resources :users
  resources :sessions
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  validates :event_name, presence: true, uniqueness: true
  validates :description, presence: true
  belongs_to :creator, class_name: 'User'
  has_many :attendances, foreign_key: 'attended_event_id', class_name: 'Attendance', dependent: :destroy
  has_many :attendees, through: :attendances, source: :attendee, class_name: 'User'

  scope :upcoming_events, -> { where('date >= ?', Date.today).order(date: :desc) }
  scope :previous_events, -> { where('date < ?', Date.today).order(date: :desc) }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :authorized, only: %i[show edit update destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @prev_event = Event.previous_events
    @fut_event = Event.upcoming_events
  end

  # GET /events/1
  # GET /events/1.json
  def show
    set_event
    @events = Event.all
  end

  def attend
    set_event
    user = current_user
    user.attendances.build(attended_event_id: @event.id).save
    flash[:notice] = "User #{user.username} added to attend #{@event.description}"
    redirect_to @event
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to '/welcome', notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:event_name, :description, :date)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container-fluid d-flex flex-column align-items-center justify-content-center">
    <div class="field">
      <%= form.label :event_name %>
      <%= form.text_field :event_name %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>

    <div class="field">
      <%= form.label :date %>
      <%= form.date_select :date %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>  
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th class="text-info">Event name</th>
      <th>Description</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.event_name %></td>
        <td><%= event.description %></td>
        <td><%= event.date %></td>
        <td><%= link_to 'Show', event %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %><br>
<%= link_to 'Back', '/welcome' %>


<div class="container-fluid">
  <div class="row border d-flex align-items-center border-info">
    <div class="col-6 text-center">
      <h2 class="text-uppercase">Upcoming Events</h2>
    </div>
    <div class="col-6 text-center">
      <h2 class="text-uppercase">Previous Events</h2>
    </div>
  </div>
  <div class="row border border-info d-flex">
    <div class="col-6 text-center d-flex flex-column">
      <% @fut_event.each do |fut| %>
        <p><%= fut.description%></p>
      <% end %>
    </div>
    <div class="col-6 text-center d-flex flex-column">
      <% @prev_event.each do |prev| %>
        <p><%= prev.description%></p>
      <% end %> 
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container-fluid d-flex flex-column align-items-center justify-content-center">
  <h1 class="text-uppercase text-info">New Event</h1>

  <%= render 'form', event: @event %>

  <%= link_to 'Back', events_path %>
</div>  

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<%if !@event.creator.nil?%>
<p>
  <strong>Author:</strong>
  <%= @event.creator.name%>
</p>
<% else %>
  <strong>Your event doesn't have a creator</strong>
<%end%>
<p>
  <strong>Description</strong>
  <%= @event.description%>
</p>

<p>
  <strong>Description</strong>
  <%= current_user.name%>
</p>

<td><%= link_to 'Attend', attendy_path(@event), class:"button"%></td>
<%= link_to 'Back', '/welcome' %>

  
  <tr><h1>List of attended</h1>
    <% @event.attendees.each do |user| %>
        <div>
          <strong><%= user.username %> </strong>       
        </div>
    <% end %>
  <tr>
  